blank_issues_enabled: false
contact_links:
  - name: Suggest a New Resource
    url: https://github.com/jonathondilworth/systems-gov-resources/issues/new?template=suggest-new-resource.md
    about: Use this link to suggest a new resource to be added to the repository.